name: wheat_plant_density_p2pnet_env
channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.9
  - numpy=1.23
  - scipy
  - matplotlib
  - pillow
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - cudatoolkit=11.7

